apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: animatedbook-viewer
  namespace: default
spec:
  rules:
  - services: ["animatedbook.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-animatedbook-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "animatedbook-viewer"
