apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: guestbook-viewer
  namespace: default
spec:
  rules:
  - services: ["guestbook.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-guestbook-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "guestbook-viewer"
